name: pages
description: Data Visualization Examples - Interactive showcase of all widgets
publish_to: none
resolution: workspace

version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  data_visualization:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/world.geo.json
