name: dv_grid
description: Grid lines for chart backgrounds.
repository: https://github.com/gsmlg-dev/data_visualization/tree/main/packages/dv_grid
homepage: https://github.com/gsmlg-dev/data_visualization
publisher: gsmlg.dev
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dv_scale:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
