name: dv_hierarchy
description: Hierarchical data structures and layout algorithms.
repository: https://github.com/gsmlg-app/data_visualization/tree/main/packages/dv_hierarchy
homepage: https://gsmlg-app.github.io/data_visualization/
version: 1.0.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dv_vendor:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
