name: dv_mock_data
description: Mock data generators for testing and demos.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dv_vendor:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
