name: dv_drag
description: Drag interaction for chart elements.
repository: https://github.com/gsmlg-dev/data_visualization/tree/main/packages/dv_drag
homepage: https://github.com/gsmlg-dev/data_visualization
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dv_point:
  dv_event:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
