name: dv_clip_path
description: Clip path definitions for chart areas.
repository: https://github.com/gsmlg-dev/data_visualization/tree/main/packages/dv_clip_path
homepage: https://github.com/gsmlg-dev/data_visualization
publisher: gsmlg.dev
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
