name: dv_geo
description: Flutter widgets for geographic visualizations.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dv_geo_core:
  dv_point:
  dv_shape:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
