name: dv_curve
description: Curve generators for smooth line interpolation.
repository: https://github.com/gsmlg-dev/data_visualization/tree/main/packages/dv_curve
homepage: https://github.com/gsmlg-dev/data_visualization
version: 1.0.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dv_point:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
