name: dv_voronoi
description: Voronoi diagrams derived from Delaunay triangulation.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dv_point:
  dv_delaunay:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
