name: dv_voronoi
description: Voronoi diagrams derived from Delaunay triangulation.
repository: https://github.com/gsmlg-dev/data_visualization/tree/main/packages/dv_voronoi
homepage: https://github.com/gsmlg-dev/data_visualization
publisher: gsmlg.dev
version: 1.0.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dv_point:
  dv_delaunay:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
