name: dv_heatmap
description: Heatmap visualization components.
repository: https://github.com/gsmlg-dev/data_visualization/tree/main/packages/dv_heatmap
homepage: https://github.com/gsmlg-dev/data_visualization
publisher: gsmlg.dev
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dv_scale:
  dv_axis:
  dv_gradient:
  dv_tooltip:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
