name: dv_stats
description: Statistical functions for data analysis.
repository: https://github.com/gsmlg-dev/data_visualization/tree/main/packages/dv_stats
homepage: https://github.com/gsmlg-dev/data_visualization
publisher: gsmlg.dev
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dv_vendor:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
