name: dv_scale
description: Scale functions for data visualization - linear, log, band, ordinal, etc.
repository: https://github.com/gsmlg-app/data_visualization/tree/main/packages/dv_scale
homepage: https://gsmlg-app.github.io/data_visualization/
version: 1.0.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dv_vendor:
  dv_point:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
