name: dv_delaunay
description: Delaunay triangulation for point sets.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dv_point:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
