name: dv_zoom
description: Zoom and pan interaction for charts.
repository: https://github.com/gsmlg-app/data_visualization/tree/main/packages/dv_zoom
homepage: https://github.com/gsmlg-app/data_visualization
version: 1.0.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  dv_point:
  dv_event:
  dv_scale:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
