name: dv_zoom
description: Zoom and pan interaction for charts.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  dv_point:
  dv_event:
  dv_scale:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
