name: dv_tooltip
description: Tooltip component for chart data display.
repository: https://github.com/gsmlg-app/data_visualization/tree/main/packages/dv_tooltip
homepage: https://github.com/gsmlg-app/data_visualization
version: 1.0.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dv_point:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
