name: dv_tooltip
description: Tooltip component for chart data display.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dv_point:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
